upstreams:
  - name: "stub-server-1"
    servers:
      - url: "http://localhost:8080"
        status: false
      - url: "http://localhost:8081"
        status: false
      - url: "http://localhost:8082"
        status: false
    healthCheck:
      url: "/health"
      interval: 5s
      timeout: 1s
    rateLimit:
      limit: 0
      interval: 1m

  - name: "stub-server-2"
    servers:
      - url: "http://localhost:8083"
        status: false
      - url: "http://localhost:8084"
        status: false
    healthCheck:
      url: "/health"
      interval: 2s
      timeout: 1s
    rateLimit:
      limit: 0
      interval: 1m

  
    
      