upstreams:
  - name: "stub-server-1"
    servers:
      - "http://localhost:8080"
      - "http://localhost:8081"
      - "http://localhost:8082"
    healthCheck:
      url: "/health"
      interval: 5s
      timeout: 1s
    rateLimit:
      limit: 100
      interval: 1m

  - name: "stub-server-2"
    servers:
      - "http://localhost:8083"
      - "http://localhost:8084"
    healthCheck:
      url: "/health"
      interval: 2s
      timeout: 1s
    rateLimit:
      limit: 100
      interval: 1m

  
    
      