upstreams:
  - name: "stub-server-1"
    servers:
      - url: "http://localhost:8080"
        status: true
      - url: "http://localhost:8081"
        status: true
    healthCheck:
      url: "/health"
      interval: 5s
      timeout: 1s
      enabled: true
    rateLimit:
      limit: 100
      interval: 1m
      enabled: false
    lbType: "leastconn"

  - name: "stub-server-2"
    servers:
      - url: "http://localhost:8082"
        status: true
      - url: "http://localhost:8083"
        status: true
    healthCheck:
      url: "/health"
      interval: 2s
      timeout: 1s
      enabled: true
    rateLimit:
      limit: 100
      interval: 1m
      enabled: false
    lbType: "leastconn"

  - name: "stub-server-3"
    servers:
      - url: "http://localhost:8084"
        status: true
    healthCheck:
      url: "/health"
      interval: 2s
      timeout: 1s
      enabled: true
    rateLimit:
      limit: 100
      interval: 1m
      enabled: false
    lbType: "leastconn"


  
    
      